// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaffDatabase.Model;

namespace StaffDatabase.Migrations
{
    [DbContext(typeof(StaffDatabaseContext))]
    [Migration("20191124231259_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("StaffDatabase.Model.StaffMember", b =>
                {
                    b.Property<int>("IrdNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellPh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fname")
                        .HasColumnType("TEXT");

                    b.Property<int>("HomePh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mname")
                        .HasColumnType("TEXT");

                    b.Property<int>("OffExtension")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("IrdNo");

                    b.ToTable("StaffMember");
                });
#pragma warning restore 612, 618
        }
    }
}
